### ISSUE TITLE
Question: Is the Splunk ITSM module required? 

### ISSUE THREAD

**Issue by jauyzed** [guilhemmarchand/telegraf-kafka#72]
Hello,

Is the ITSI module required to get the level of monitoring/logging shown in the diagram? 

Sorry, the document does not specify if ITSI is required or not. 

Thank you.

**Comment by guilhemmarchand** [comment]
Hi @jauyzed 

No, ITSI is not required as such, it might appear in some screenshots within the documentation to demonstrate the possible use cases, but ITSI is not a dependency.
As you might have noticed however, if you have ITSI there is an integration available, but this is optional.

Guilhem

**Comment by jauyzed** [comment]
Appreciate the quick reply @guilhemmarchand.
